### ISSUE TITLE
Disable Message Box on Connect Page

### ISSUE THREAD

**Issue by ghost** [AWildBeard/WildChat#2]
If you're on the connect page and you accidentally type the streamer name into the chat box then you've just sent it as a message in your current chat, woops.

Not the biggest issue ever, but it's a little embarrassing.

**Comment by AWildBeard** [comment]
righto good idea! gettin right on it!

**Comment by AWildBeard** [comment]
Fixed on commit: 5ed9a509426b666a7b3bc1e7d66e540a69bbf154
Closing.
