### ISSUE TITLE
[ENHANCEMENT] Make it clearer what channel the user is connected to.

### ISSUE THREAD

**Issue by AWildBeard** [AWildBeard/WildChat#5]
[//]: # "If what you have to say is a feature request, please delete from 'Steps to reproduce' and down"

[//]: # "Screenshots are preffered if the issue is obvious."

### Expected behavior
[//]: # "This will be something similar to 'When my friend says hello it says hello'"

- When the client is connected to a channel, clearly distinguish, in some way, what channel the client is connected to constantly throughout the life of the connection to that channel.

### Actual behavior
[//]: # "This will be something similar to 'When my friend says hello it doesn't say hello'"

- Current channel connections are only shown as a status message in the message area.

**Comment by hexdsl** [comment]
This would improve quality of life :)

**Comment by AWildBeard** [comment]
Solved in bc08a14209dc8f1043007e3571b4a593eedd4a6f
